// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvxyycuukrkjlmaytqok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2eHl5Y3V1a3JramxtYXl0cW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzA2MTQsImV4cCI6MjA2MzkwNjYxNH0.BkuGbMjD_PrfNDEj6Nlp5lQZQb2o66p030dALjEwzjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);